dts vcc,BTN_0 ms,2-lan no wan,net4g start if sim_ready;check AT at qmi

diff --git a/package/base-files/files/etc/rc.button/failsafe b/package/base-files/files/etc/rc.button/failsafe
--- a/package/base-files/files/etc/rc.button/failsafe
+++ b/package/base-files/files/etc/rc.button/failsafe
@@ -1,5 +1,6 @@
 #!/bin/sh
 
-[ "${TYPE}" = "switch" ] || echo ${BUTTON} > /tmp/failsafe_button
+echo "SKIP failsafe; ${TYPE} at ${BUTTON}"
+#[ "${TYPE}" = "switch" ] || echo ${BUTTON} > /tmp/failsafe_button
 
 return 0
